"""Quantile tables for mods\\rookies.dll: what the game's generated players look like against real established players.

The free-agent generator (FUN_68040da0) rolls new players whose peak ratings are bunched in the middle: no stars, few
scrubs. rookies.dll maps each new player's peak ratings, class by class, from the generated distribution onto the real
one. This script measures both from two PYR files and writes the C header the mod compiles in:

    python3 -m work.lahman.rookietable --base 1997.PYR --gen LATER.PYR --year 1997 --out src-latest/mods/rookies_table.h

--base is a season's PYR as shipped (the real players); --gen is a PYR of the same association after several seasons
of stock play (no rookies.dll), whose players not in --base are the generated ones. The target is the base players
aged 26 to 31 on April 1 of --year (younger real players carry Sierra's inflated projections). Only the numbers go in
the header, no game data.
"""

import argparse
import datetime
import struct
import sys

from . import ratings as R

POINTS = 21                      # 0%, 5%, ... 100%
TARGET_AGES = (26, 32)           # [lo, hi) on April 1 of the base year

# class name -> (pitchers?, rating indexes). Index: 0 contact, 1 power, 2 speed, 3 arm, 4 hold, 5 endurance,
# 6 control, 7..13 pitches, 14..22 fielding P..RF. A pitcher is a player with any nonzero pitch.
CLASSES = (
    ('H_CONTACT', False, (0,)), ('H_POWER', False, (1,)), ('H_SPEED', False, (2,)), ('H_ARM', False, (3,)),
    ('H_FIELD', False, tuple(range(15, 23))),
    ('P_ARM', True, (3,)), ('P_HOLD', True, (4,)), ('P_ENDUR', True, (5,)), ('P_CONTROL', True, (6,)),
    ('P_PITCH', True, tuple(range(7, 14))),
)


def quantiles(values, n=POINTS):
    """n evenly spaced order statistics of values (nearest rank), lowest to highest."""
    v = sorted(values)
    if not v:
        raise ValueError('no values')
    return [v[round(i * (len(v) - 1) / (n - 1))] for i in range(n)]


def pid_of(rec):
    return struct.unpack_from('<H', rec, 0)[0]


def is_pitcher(rec):
    return any(rec[R.PEAK + k] for k in range(7, 14))


def age_on(rec, day):
    born = struct.unpack_from('<I', rec, 0x1a)[0]
    return (R.serial(day) - born) / 365.25


def class_values(recs, pitchers, ks):
    return [r[R.PEAK + k] for r in recs if is_pitcher(r) == pitchers for k in ks if r[R.PEAK + k]]


def tables(base_recs, gen_recs, year):
    """{class: (gen quantiles, target quantiles)} from the base records and the later file's records."""
    base_ids = {pid_of(r) for r in base_recs}
    new = [r for r in gen_recs if pid_of(r) >= 100 and pid_of(r) not in base_ids]
    day = datetime.date(year, 4, 1)
    lo, hi = TARGET_AGES
    target = [r for r in base_recs if pid_of(r) >= 100 and lo <= age_on(r, day) < hi]
    out = {}
    for name, pitchers, ks in CLASSES:
        g, t = class_values(new, pitchers, ks), class_values(target, pitchers, ks)
        if not g or not t:
            raise ValueError('%s: no %s ratings' % (name, 'generated' if not g else 'target'))
        out[name] = (quantiles(g), quantiles(t))
    return out, len(new), len(target)


def header(tabs, n_gen, n_target, year):
    lines = ['/* rookies_table.h: generated by work/lahman/rookietable.py, do not edit. %d generated players against'
             % n_gen, '   %d real players aged %d to %d in %d. Peak rating quantiles at 0%%, 5%%, ... 100%%. */'
             % (n_target, TARGET_AGES[0], TARGET_AGES[1] - 1, year),
             '#define RQ_POINTS %d' % POINTS, '#define RQ_CLASSES %d' % len(CLASSES)]
    lines.append('enum { %s };' % ', '.join('RC_%s' % name for name, _, _ in CLASSES))
    lines.append('static const char *const RQ_NAMES[RQ_CLASSES] = {%s};'
                 % ', '.join('"%s"' % name.lower() for name, _, _ in CLASSES))
    for label, side in (('RQ_GEN', 0), ('RQ_TGT', 1)):
        lines.append('static const unsigned char %s[RQ_CLASSES][RQ_POINTS] = {' % label)
        for name, _, _ in CLASSES:
            lines.append('    {%s},  /* %s */' % (','.join(str(x) for x in tabs[name][side]), name.lower()))
        lines.append('};')
    return '\n'.join(lines) + '\n'


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split('\n\n')[0])
    ap.add_argument('--base', required=True, help='PYR as shipped for --year (read only)')
    ap.add_argument('--gen', required=True, help='PYR of the same association after stock seasons (read only)')
    ap.add_argument('--year', type=int, required=True)
    ap.add_argument('--out', required=True, help='header to write')
    a = ap.parse_args(argv)
    _, base = R.read_pyr(a.base)
    _, gen = R.read_pyr(a.gen)
    tabs, n_gen, n_target = tables(base, gen, a.year)
    with open(a.out, 'w') as fh:
        fh.write(header(tabs, n_gen, n_target, a.year))
    print('%d generated, %d target players -> %s' % (n_gen, n_target, a.out))
    return 0


if __name__ == '__main__':
    sys.exit(main())
