[PlayBalance]

;DEFENSIVE POSITION
UseINIDefpos=1

;Outfield position
outfieldPosPctVeryShallow=55
outfieldPosPctShallow=60
outfieldPosPctNormal=64
outfieldPosPctDeep=67
outfieldPosPctVeryDeep=70

;normal was 60
normalPosLFPct=75
normalPosLFAngle=24
normalPosCFPct=75
normalPosCFAngle=0
normalPosRFPct=75
normalPosRFAngle=-24

guardLeftPosLFPct=55
guardLeftPosLFAngle=30
guardLeftPosCFPct=55
guardLeftPosCFAngle=5
guardLeftPosRFPct=45
guardLeftPosRFAngle=-25

guardRightPosLFPct=45
guardRightPosLFAngle=25
guardRightPosCFPct=55
guardRightPosCFAngle=-5
guardRightPosRFPct=55
guardRightPosRFAngle=-30

defPosHighPull=65
defPosLowPull=39
defPosHighPullExtra=58
defPosLowPullExtra=44
defPosHighPower=85
defPosLowPower=20

; Infielder positioning in "Normal" situations
normalPos1BDist=130
normalPos1BAngle=-35
normalPos2BDist=140
normalPos2BAngle=-15
normalPosSSDist=140
normalPosSSAngle=15
normalPos3BDist=130
normalPos3BAngle=35
;
; Infielder positioning in "Guard Lines" situations
guardLinesPos1BDist=120
guardLinesPos1BAngle=-40
guardLinesPos2BDist=140
guardLinesPos2BAngle=-15
guardLinesPosSSDist=140
guardLinesPosSSAngle=15
guardLinesPos3BDist=120
guardLinesPos3BAngle=40
;
; Infielder positioning in "Cutoff Run" situation
cutoffRunPos1BDist=90
cutoffRunPos1BAngle=-35
cutoffRunPos2BDist=105
cutoffRunPos2BAngle=-15
cutoffRunPosSSDist=105
cutoffRunPosSSAngle=15
cutoffRunPos3BDist=90
cutoffRunPos3BAngle=35

; Infielder positioning for "Double Play" situations
doublePlayPos1BDist=120
doublePlayPos1BAngle=-35
doublePlayPos2BDist=140
doublePlayPos2BAngle=-12
doublePlayPosSSDist=140
doublePlayPosSSAngle=12
doublePlayPos3BDist=120
doublePlayPos3BAngle=35

; Outfielder positioning for "Guard Right-field Line" situations
guardRightPosLFPct=45
guardRightPosLFAngle=25
guardRightPosCFPct=69
guardRightPosCFAngle=-5
guardRightPosRFPct=65
guardRightPosRFAngle=-30


; MAXIMUM CHASE DISTANCES
infieldMaxChaseDist=33
pitcherMaxChaseDist=90
outfieldMinChaseDist=150

; FIELDER CATCH CHANCE
catchBaseChance=90
catchFADiv=7
catchChanceDiving=-20
catchChanceLeaping=-15
catchChanceLessThan1Sec=-10
catchChancePerTenth=-2
catchChancePitcherAdjust=-10
catchChanceCatcherAdjust=8
catchChanceFirstBaseAdjust=10
catchChanceSecondBaseAdjust=0
catchChanceThirdBaseAdjust=0
catchChanceShortStopAdjust=0
catchChanceLeftFieldAdjust=5
catchChanceCenterFieldAdjust=5
catchChanceRightFieldAdjust=5

delayBasePitcher=15
delayFAPctPitcher=-8
delayBaseCatcher=14
delayFAPctCatcher=-5
delayBaseFirstBase=11
delayFAPctFirstBase=-6
delayBaseSecondBase=14
delayFAPctSecondBase=-6
delayBaseThirdBase=12
delayFAPctThirdBase=-6
delayBaseShortStop=14
delayFAPctShortStop=-6
delayBaseLeftField=16
delayFAPctLeftField=-7
delayBaseCenterField=16
delayFAPctCenterField=-7
delayBaseRightField=16
delayFAPctRightField=-7 

;THROWS 
maxThrowDistBase=170
maxThrowDistASPct=90
throwHeightPct=58

throwSpeedIFBase=57
throwSpeedIFDistPct=3
throwSpeedIFMax=90
throwSpeedOFBase=48
throwSpeedOFDistPct=3
throwSpeedOFMax=82

; CHANCE OF THROWING ERRORS
goodThrowBase=90
goodThrowFAPct=10
goodThrowChancePitcher=0
goodThrowChanceCatcher=-25
goodThrowChanceFirstBase=0
goodThrowChanceSecondBase=10
goodThrowChanceThirdBase=0
goodThrowChanceShortStop=0
goodThrowChanceLeftField=-11
goodThrowChanceCenterField=-11
goodThrowChanceRightField=-11

;STEALS

longLeadSpeed=54
pickoffScareSpeed=60
;56
StealChanceBase=59
stealChance00Count=-10
stealChance01Count=-10
stealChance02Count=-20
stealChance10Count=10
stealChance11Count=0
stealChance12Count=-10
stealChance20Count=20
stealChance21Count=10
stealChance22Count=0
stealChance30Count=15
stealChance31Count=15
stealChance32Count=20
offManStealChancePct=100

stealChanceVerySlowThresh=29
stealChanceSlowThresh=39
stealChanceMedThresh=54
stealChanceFastThresh=70

stealChanceVerySlowAdjust=-80
stealChanceSlowAdjust=-35
stealChanceMedAdjust=-5
stealChanceFastAdjust=10
stealChanceVeryFastAdjust=20

stealChanceVeryLowHoldThresh=19
stealChanceLowHoldThresh=39
stealChanceMedHoldThresh=59
stealChanceHighHoldThresh=74

stealChanceVeryLowHoldAdjust=30
stealChanceLowHoldAdjust=15
stealChanceMedHoldAdjust=5
stealChanceHighHoldAdjust=-20
stealChanceVeryHighHoldAdjust=-40

stealChancePitcherFaceAdjust=-10
stealChancePitcherBackAdjust=5
stealChancePitcherWindupAdjust=5
stealChancePitcherWildAdjust=0

stealChanceOnFirst2OutHighCHThresh=59
stealChanceOnFirst2OutHighCHAdjust=10
stealChanceOnFirst2OutLowCHThresh=39
stealChanceOnFirst2OutLowCHAdjust=-10

stealChanceOnFirst01OutHighCHThresh=59
stealChanceOnFirst01OutHighCHAdjust=-5
stealChanceOnFirst01OutLowCHThresh=39
stealChanceOnFirst01OutLowCHAdjust=5

stealChanceOnSecond0OutAdjust=-35
stealChanceOnSecond1OutAdjust=-30
stealChanceOnSecond2OutAdjust=-60
stealChanceOnSecondHighCHThresh=59
stealChanceOnSecondHighCHAdjust=-5

stealChanceWayBehindThresh=-3
stealChanceWayBehindAdjust=-60

pitchScoringOut=1
pitchScoringStrikeOut=2
pitchScoringOffRun=2
pitchScoringInnsAfter4=2
pitchScoringWalk=-1
pitchScoringHit=-2
pitchScoringConsHit=-1
pitchScoringRun=-2
pitchScoringER=-2
pitchScoringHR=-3
pitchScoringWP=-2

;PITCHING!!!

;FATIGUE
tiredPitchRatPct=90
tiredASPct=90
exhaustedPitchRatPct=75
exhaustedASPct=75

;PICKOFF THROWS
holdChanceBase=0
holdChanceMinRunnerSpeed=45
holdChanceAdjust=100

;CONTROL AND MOTION
effCOPct=45
effMOPct=110
controlBoxIncreaseEffCOPct=22

;RELIEF PITCHING
posPlayerPitchingRuns=12  

speedReductionBase=3
speedReductionRange=3
speedReductionEffMOPct=5

pitchRatVariationCount=1
pitchRatVariationFaces=5
pitchRatVariationBase=-2

;PITCH OBJECTIVES
nonEstablishedPitchTypeAdjust=0
primaryPitchTypeAdjust=50

pitchObj00CountEstablishWeight=0
pitchObj00CountOutsideWeight=34
pitchObj00CountBestWeight=0
pitchObj00CountBestCenterWeight=0
pitchObj00CountFastCenterWeight=0
pitchObj00CountPlusWeight=66

pitchObj01CountEstablishWeight=0
pitchObj01CountOutsideWeight=46
pitchObj01CountBestWeight=0
pitchObj01CountBestCenterWeight=0
pitchObj01CountFastCenterWeight=0
pitchObj01CountPlusWeight=54

pitchObj02CountEstablishWeight=0
pitchObj02CountOutsideWeight=68
pitchObj02CountBestWeight=25
pitchObj02CountBestCenterWeight=0
pitchObj02CountFastCenterWeight=0
pitchObj02CountPlusWeight=7

pitchObj10CountEstablishWeight=0
pitchObj10CountOutsideWeight=10
pitchObj10CountBestWeight=0
pitchObj10CountBestCenterWeight=0
pitchObj10CountFastCenterWeight=0
pitchObj10CountPlusWeight=90

pitchObj11CountEstablishWeight=0
pitchObj11CountOutsideWeight=32
pitchObj11CountBestWeight=5
pitchObj11CountBestCenterWeight=0
pitchObj11CountFastCenterWeight=0
pitchObj11CountPlusWeight=63

pitchObj12CountEstablishWeight=0
pitchObj12CountOutsideWeight=45
pitchObj12CountBestWeight=35
pitchObj12CountBestCenterWeight=0
pitchObj12CountFastCenterWeight=0
pitchObj12CountPlusWeight=20

pitchObj20CountEstablishWeight=0
pitchObj20CountOutsideWeight=0
pitchObj20CountBestWeight=0
pitchObj20CountBestCenterWeight=13
pitchObj20CountFastCenterWeight=20
pitchObj20CountPlusWeight=67

pitchObj21CountEstablishWeight=0
pitchObj21CountOutsideWeight=0
pitchObj21CountBestWeight=15
pitchObj21CountBestCenterWeight=0
pitchObj21CountFastCenterWeight=17
pitchObj21CountPlusWeight=68

pitchObj22CountEstablishWeight=0
pitchObj22CountOutsideWeight=25
pitchObj22CountBestWeight=30
pitchObj22CountBestCenterWeight=0
pitchObj22CountFastCenterWeight=0
pitchObj22CountPlusWeight=45

pitchObj30CountEstablishWeight=0
pitchObj30CountOutsideWeight=0
pitchObj30CountBestWeight=0
pitchObj30CountBestCenterWeight=15
pitchObj30CountFastCenterWeight=45
pitchObj30CountPlusWeight=40

pitchObj31CountEstablishWeight=0
pitchObj31CountOutsideWeight=0
pitchObj31CountBestWeight=5
pitchObj31CountBestCenterWeight=5
pitchObj31CountFastCenterWeight=30
pitchObj31CountPlusWeight=60

pitchObj32CountEstablishWeight=0
pitchObj32CountOutsideWeight=15
pitchObj32CountBestWeight=20
pitchObj32CountBestCenterWeight=0
pitchObj32CountFastCenterWeight=20
pitchObj32CountPlusWeight=45

;WILD PITCHES
wildCatchChanceBase=98
wildCatchChanceFAPct=15
wildCatchChanceOppMod=-10
wildCatchChanceHighMod=-5

;PITCH CONTROL ZONES AND SPEEDS
fbSpeedBase=68
fbSpeedRange=2
fbSpeedASPct=30

cbSpeedBase=53
cbSpeedRange=2
cbSpeedASPct=30

cuSpeedBase=48
cuSpeedRange=2
cuSpeedASPct=30

slSpeedBase=61
slSpeedRange=2
slSpeedASPct=30

sbSpeedBase=53
sbSpeedRange=2
sbSpeedASPct=30

kbSpeedBase=63
kbSpeedRange=2
kbSpeedASPct=0

siSpeedBase=62
siSpeedRange=2
siSpeedASPct=30

fbControlBoxWidth=1
fbControlBoxHeight=1

cbControlBoxWidth=1
cbControlBoxHeight=1

cuControlBoxWidth=1
cuControlBoxHeight=1

slControlBoxWidth=1
slControlBoxHeight=1

sbControlBoxWidth=1
sbControlBoxHeight=1

kbControlBoxWidth=1
kbControlBoxHeight=1

siControlBoxWidth=1
siControlBoxHeight=1

stControlBoxWidth=1
stControlBoxHeight=1

fbBreakBaseWidth=0
fbBreakBaseHeight=0
fbBreakRangeWidth=0
fbBreakRangeHeight=0

cbBreakBaseWidth=2
cbBreakBaseHeight=-5
cbBreakRangeWidth=2
cbBreakRangeHeight=-1

cuBreakBaseWidth=0
cuBreakBaseHeight=-3
cuBreakRangeWidth=0
cuBreakRangeHeight=-2

slBreakBaseWidth=1
slBreakBaseHeight=0
slBreakRangeWidth=2
slBreakRangeHeight=-1

sbBreakBaseWidth=-2
sbBreakBaseHeight=-4
sbBreakRangeWidth=-2
sbBreakRangeHeight=-1

kbBreakBaseWidth=0
kbBreakBaseHeight=-4
kbBreakRangeWidth=2
kbBreakRangeHeight=-2

siBreakBaseWidth=0
siBreakBaseHeight=-2
siBreakRangeWidth=0
siBreakRangeHeight=-1

stBreakBaseWidth=0
stBreakBaseHeight=0
stBreakRangeWidth=0
stBreakRangeHeight=0

;BATTING!!!

;Strike Zone
sureStrikeDist=3
closeStrikeDist=6
closeBallDist=5

;ID
idRatingBase=5
idRatingCHPct=140
idRatingExpPct=35
idRatingPitchRatPct=45

idRatingTypeWeight=100
idRatingLocWeight=100
idRatingTimingWeight=100

timingVeryBadThresh=62
timingVeryBadCount=2
timingVeryBadFaces=35
timingVeryBadBase=-35

timingBadThresh=88
timingBadCount=2
timingBadFaces=31
timingBadBase=-31

timingMedThresh=94
timingMedCount=3
timingMedFaces=22
timingMedBase=-33

timingGoodThresh=99
timingGoodCount=9
timingGoodFaces=7
timingGoodBase=-31

timingVeryGoodCount=14
timingVeryGoodFaces=4
timingVeryGoodBase=-28

;DISCIPLINE
disciplineRatingBase=0
disciplineRatingPct=90
disciplineRatingCHPct=100
disciplineRatingExpPct=50

disciplineRatingNoPitchesAdjust=20
disciplineRatingScoringPosAdjust=-10
disciplineRatingOnThird01OutsAdjust=-10
disciplineRatingPlusZoneAdjust=10
disciplineRatingMinusZoneAdjust=-10
disciplineRatingLocNextToLookAdjust=-30
disciplineRatingFBDownMiddleAdjust=-40

disciplineRating00CountAdjust=25
disciplineRating01CountAdjust=00
disciplineRating02CountAdjust=-10
disciplineRating10CountAdjust=0
disciplineRating11CountAdjust=0
disciplineRating12CountAdjust=0
disciplineRating20CountAdjust=-5
disciplineRating21CountAdjust=-5
disciplineRating22CountAdjust=0
disciplineRating30CountAdjust=70
disciplineRating31CountAdjust=0
disciplineRating32CountAdjust=0

;ADJUSTMENT UNITS
adjustUnitsCHPct=35
adjustUnitsPowerPct=25
adjustUnitsContactPct=170
adjustUnitsBuntPct=500
adjustUnitsDiag=2
adjustUnitsHoriz=1
adjustUnitsVert=1

adjustUnitsSpeedUpLowGeared=1
adjustUnitsSpeedUpHighGeared=8
adjustUnitsSlowDownLowGeared=1
adjustUnitsSlowDownHighGeared=4

;CHECK SWING CHANCES
checkChanceBasePower=30
checkChanceBaseNormal=40
checkChanceBaseContact=50
checkChanceBaseBunt=100
checkChanceCHPctPower=10
checkChanceCHPctNormal=20
checkChanceCHPctContact=30
checkChanceCHPctBunt=40
failedCheckContactChance=5

;PITCH LOOK ADJUSTMENTS
lookPrimaryType00CountAdjust=0
lookPrimaryType01CountAdjust=0
lookPrimaryType02CountAdjust=0
lookPrimaryType10CountAdjust=0
lookPrimaryType11CountAdjust=0
lookPrimaryType12CountAdjust=0
lookPrimaryType20CountAdjust=20
lookPrimaryType21CountAdjust=15
lookPrimaryType22CountAdjust=0
lookPrimaryType30CountAdjust=20
lookPrimaryType31CountAdjust=25
lookPrimaryType32CountAdjust=19

lookBestType00CountAdjust=0
lookBestType01CountAdjust=0
lookBestType02CountAdjust=25
lookBestType10CountAdjust=0
lookBestType11CountAdjust=0
lookBestType12CountAdjust=35
lookBestType20CountAdjust=0
lookBestType21CountAdjust=0
lookBestType22CountAdjust=30
lookBestType30CountAdjust=0
lookBestType31CountAdjust=10
lookBestType32CountAdjust=20

;BATTING PHYSICS
swingSpeedBase=64
swingSpeedPHPct=6
swingSpeedPowerAdjust=2
swingSpeedNormalAdjust=0
swingSpeedContactAdjust=-2
swingSpeedBuntAdjust=-100

averagePitchSpeed=91
fastPitchBatSlowdownPct=103
slowPitchBatSpeedupPct=85

batPowerHandleBase=25
batPowerDullBase=50
batPowerSweetBase=98
batPowerEndBase=50
batPowerHandleRange=5
batPowerDullRange=10
batPowerSweetRange=4
batPowerEndRange=10

;TRAJECTORIES
hitAngleCountPower=3
hitAngleFacesPower=15
hitAngleBasePower=8

hitAngleCountNormal=3
hitAngleFacesNormal=14
hitAngleBaseNormal=8

hitAngleCountContact=3
hitAngleFacesContact=14
hitAngleBaseContact=8

hitAngleCountBunt=10
hitAngleFacesBunt=7
hitAngleBaseBunt=-10

; SWING ANGLE

swingAngleTenthDegreesBase=140
swingAngleTenthDegreesRange=0
swingAngleTenthDegreesGFPct=0
swingAngleTenthDegreesPowerAdjust=10
swingAngleTenthDegreesContactAdjust=-10
swingAngleTenthDegreesHighAdjust=30
swingAngleTenthDegreesLowAdjust=-30
swingAngleTenthDegreesOutsideAdjust=-10

;SPEED
speedBase=19
speedPct=6

hbpBatterStepOutChance=95

couldBeCaughtSlop=-18 
shouldBeCaughtSlop=6    
generalSlop=9           
relaySlop=12   
userCatchDist=4         
computerCatchDist=3     
throwTimeSlop=6        
effortCatchDist=9   
automaticCatchDist=20               

;GAME PHYSICS
rollFrictionGrass=9
rollFrictionTurf=7
ballAirResistancePct=99
ballAltitudePct=85
ballBaseAltitude=0
ballTempPct=40
ballWindSpeedPct=45

bounceVertTurfPct=38
bounceHorizTurfPct=73
bounceVertGrassPct=36
bounceHorizGrassPct=71
bounceVertDirtPct=25
bounceHorizDirtPct=50
bounceWetAdjust=-2
bounceHotAdjust=2
bounceColdAdjust=-2


[DialogPositions]
CAMSX=323
CAMSY=290


