#!/usr/bin/env python3
"""Generates src-latest/mods/simtrace_probes.h: the small getters the simtrace targets call directly, so simtrace.c
can log their return values as 'X' events. usage: simtrace_gen.py (reads the work copy's FastSim.dll with objdump)

A callee is probed when it is game code of at most MAXLEN bytes, does not read edx before writing it, starts with push ebp / mov ebp,esp, and its stack arguments are
known: `ret N` (thiscall / stdcall, N/4 arguments) or a plain `ret` with no [ebp+8..] reference (no stack arguments).
cdecl callees with stack arguments are skipped (a thiscall wrapper would not forward them). Already-probed functions
(PB getter, RNG, runner speed, stat getters) and the targets themselves are excluded. PROBES (va, stack args) is
importable by re/sim_model.py; the probe id is the list index.
"""
import csv, os, re, subprocess, sys

DLL = '/mnt/nvme/bbpro98/work_install/FastSim.dll'
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, '..', 'src-latest', 'mods', 'simtrace_probes.h')
TARGETS = [0x68052bd5, 0x68036d52, 0x68036e91, 0x68054b0a, 0x68014f7b, 0x68023dd3, 0x68049d61, 0x680491d4,
           0x6802bde7, 0x6802be53, 0x6803122b, 0x68053248, 0x680537ad, 0x68053b36]
KNOWN = {0x68003170, 0x68082999, 0x680829dc, 0x68082a2d, 0x68082ae1, 0x68038e10, 0x6803e1b2, 0x6803da2b,
         0x6803e2e1, 0x6803df0d, 0x6803deec}
MAXLEN = 300
LIB = 0x68082000   # FUN_68082xxx and up: CRT, file I/O, asserts
STARTS = sorted(int(r[0], 16) for r in csv.reader(open('/mnt/nvme/bbpro98/index/FastSim/_functions.tsv'),
                                                    delimiter='\t') if r[0] != 'addr')


SIGS = {}   # Ghidra signature line per function (the first line with a '(' outside comments), for the return type
_cur, _cmt = None, False
for _l in open('/mnt/nvme/bbpro98/index/FastSim/_all.c', errors='replace'):
    if _l.startswith('// ==== '): _cur, _cmt = int(_l.split()[2], 16), False
    elif _cur is not None:
        if _l.lstrip().startswith('/*'): _cmt = True
        if not _cmt and '(' in _l: SIGS[_cur] = _l.strip(); _cur = None
        if '*/' in _l: _cmt = False
PTR_ALSO = {0x6803e377, 0x6803e39f}   # typed int by Ghidra, but return this + offset (rating slot addresses)


def dis(lo, hi):
    out = subprocess.run(['objdump', '-d', f'--start-address={lo:#x}', f'--stop-address={hi:#x}', DLL],
                         capture_output=True, text=True, check=True).stdout
    ins = []
    for l in out.splitlines():
        m = re.match(r'\s*([0-9a-f]+):\t((?:[0-9a-f]{2} )+)\s*\t?(.*)', l)
        if m: ins.append((int(m[1], 16), bytes.fromhex(m[2]), m[3].strip()))
    return ins


def end_of(va):
    return next(s for s in STARTS if s > va)


def probe_of(va):
    if va in KNOWN or va in TARGETS or va >= LIB: return None
    end = end_of(va)
    if end - va > MAXLEN: return None
    ins = dis(va, end)
    if not ins or ins[0][1] != b'\x55' or ins[1][1] != b'\x8b\xec': return None
    rets = [i for i in ins if i[2].startswith('ret')]
    if not rets: return None
    m = re.match(r'ret\s+\$0x([0-9a-f]+)', rets[0][2])
    if m: nargs = int(m[1], 16) // 4
    elif any(re.search(r'0x[0-9a-f]+\(%ebp\)', i[2]) and not re.search(r'-0x[0-9a-f]+\(%ebp\)', i[2]) for i in ins):
        return None   # cdecl with stack arguments
    else: nargs = 0
    if nargs > 2: return None
    for _, _, txt in ins:   # fastcall with a second register argument: the thiscall wrapper does not keep edx
        if '%edx' in txt or '%dl' in txt or '%dx' in txt:
            ops = txt.split(None, 1)
            dst_only = ops[0] in ('mov', 'movzbl', 'movsbl', 'movzwl', 'movswl', 'lea') and \
                re.search(r',%(edx|dx|dl)$', ops[1]) and 'edx' not in ops[1].rsplit(',', 1)[0] or \
                ops[0] == 'xor' and ops[1] == '%edx,%edx' or ops[0] in ('cltd', 'cdq')
            if not dst_only: return None
            break
    pro, n = b'', 0
    for a, b, _ in ins:
        pro += b
        if len(pro) >= 5: break
    if any(x[2].startswith(('call', 'jmp')) and x[0] < va + len(pro) for x in ins): return None
    sig = SIGS.get(va, '')
    return va, nargs, pro, any(i[2].startswith('call') for i in ins) | (2 if re.match(r'[\w ]+?\s*\*', sig) or va in PTR_ALSO else 0)


def main():
    callees = []
    for t in TARGETS:
        for a, b, txt in dis(t, end_of(t)):
            m = re.match(r'call\s+(?:0x)?([0-9a-f]+)$', txt)
            if m:
                c = int(m[1], 16)
                if c not in callees: callees.append(c)
    found = [p for p in map(probe_of, sorted(callees)) if p]
    probes, bigs = [p[:3] for p in found], [p[3] for p in found]
    with open(OUT, 'w') as o:
        o.write('/* generated by re/simtrace_gen.py from the work copy FastSim.dll: getters called by the simtrace targets\n'
                '   (id = index; X<n>(id) declares the handler for a getter with n stack arguments; flags 1 = makes calls, its\n'
                '   own probe events are bracketed by a Y entry marker; 2 = returns a pointer, the int it points at is logged) */\n')
        o.write('#define SIMTRACE_PROBES(X0, X1, X2) \\\n')
        o.write(' \\\n'.join(f'    X{n}({i})' for i, (va, n, pro) in enumerate(probes)) + '\n')
        o.write('static const struct { uint32_t va; uint8_t n, len, flags; uint8_t pro[9]; } XP[] = {\n')
        for (va, n, pro), big in zip(probes, bigs):
            o.write(f'    {{{va:#010x}, {n}, {len(pro)}, {int(big)}, {{{", ".join(f"{b:#04x}" for b in pro)}}}}},\n')
        o.write('};\n')
    with open(os.path.join(HERE, 'simtrace_probes.py'), 'w') as o:
        o.write('# generated by re/simtrace_gen.py: (va, stack args) per X probe id\n')
        o.write('PROBES = [' + ', '.join(f'({va:#x}, {n})' for va, n, _ in probes) + ']\n')
        o.write('NEST = [' + ', '.join(str(i) for i, b in enumerate(bigs) if b & 1) + ']\n')
        o.write('PTR = [' + ', '.join(str(i) for i, b in enumerate(bigs) if b & 2) + ']\n')
    print(f'{len(callees)} distinct callees, {len(probes)} probed')
    for i, (va, n, pro) in enumerate(probes): print(i, hex(va), n, bigs[i], SIGS.get(va, '')[:70])


if __name__ == '__main__':
    main()
